# Generated by Django 2.2.24 on 2021-10-27 01:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('editoriales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='activa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='editorial',
            name='cantidad_publicaciones',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='editorial',
            name='direccion',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='editorial',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
