# Generated by Django 2.2.24 on 2021-11-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='caratula',
            field=models.ImageField(null=True, upload_to='librosCaratulas'),
        ),
    ]
